language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

before_script: composer install

script: phpunit --bootstrap vendor/autoload.php

after_script:
- ./vendor/bin/test-reporter --stdout > codeclimate.json
- "sh -c 'if [ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" ]; then curl -X POST -d @codeclimate.json -H \"Content-Type: application/json\" -H \"User-Agent: Code Climate (PHP Test Reporter v0.1.1)\" https://codeclimate.com/test_reports  ; fi'"
